version : "2.1"
services :
    app :
        container_name : CRUDBRYAN
        restart : always
        build : .
        ports :
            - "3000:3000"
        links :
            - mongo
    mongo :
        container_name : mongoDBCrud
        image : mongo
        ports :
            - "27017:27017"